### ISSUE TITLE
initial ssh? without monitor 

### ISSUE THREAD

**Issue by saiworksandbox** [TexasInstruments/ti-bdebstrap#26]
Hello I have a TMDS64EVM board and this has no hdmi output. How do i setup the initial ssh connection from my host device? Thank you for your time

**Comment by sskartheekadivi** [comment]
Hi @saiworksandbox,

You can update `PermitRootLogin` and `PermitEmptyPasswords` in `/etc/ssh/sshd_config` as below to enable ssh login to root user without a password.

```
PermitRootLogin yes
PermitEmptyPasswords yes
```

I'll probably add a custom-hook to enable this by default in the rootfs since this is used by everyone for evaluation and development.

Thanks,
S S Kartheek Adivi

**Comment by sskartheekadivi** [comment]
This is fixed with the custom-hooks added in the new bdebstrap configs.
