### ISSUE TITLE
no-km build options missing

### ISSUE THREAD

**Issue by bobdukeCL** [TexasInstruments/ti-bdebstrap#34]
The README.md mentions:

sudo ./build.sh am62x_bookworm-no-km_09.00.00.006

But the builds.toml file no longer contains no-km build options.

Is this intentional?

**Comment by bobdukeCL** [comment]
Also, when running a build in a new Ubuntu 22.04 VM, you need to run the pip3 install command as root to ensure that the toml binary is in the path. Otherwise, the build script throws an error.

From: pip3 install toml-cli
To: sudo pip3 install toml-cli

**Comment by sskartheekadivi** [comment]
Hi @bobdukeCL , 

The removal of no-km options was intentional. Back when this project was started, we've seen a issue with dkms while installing ti-img-rogue and cryptodev modules. The dkms tried to pick Host's Linux version headers instead of version that's getting installed in the target FS. So we created km and no-km options. KM for building on target itself and -NO-KM for building on Host.

Since then, the deb packages were updated a lot and we no longer see this issue. So we unified the configs.

The README.md has to be updated to point to the latest build options that are available.

Also, Yes sudo is required for installing toml-cli. I'll be updating the README today.
